### ISSUE TITLE
数据错误，求更新

### ISSUE THREAD

**Issue by adolmad** [icaca/WclPlayerScore-WotLK#50]
尊敬的作者大大你好
今天更新的版本号：1.20.8之后，我看到不显示台服成绩和世界成绩了，只显示本服全明星成绩。但依然游戏内的显示 与网站不一致。
服务器：逐风者，角色：善惡
详见附件图一图二
希望有空可以解决一下，万分感谢。
![aaa](https://github.com/icaca/WclPlayerScore-WotLK/assets/163131461/73f55a64-88f5-41f7-ac4d-ca0cd58e836b)
![bbb](https://github.com/icaca/WclPlayerScore-WotLK/assets/163131461/1b052042-ab1a-4406-aa27-361035026e41)

**Comment by icaca** [comment]
程序改动很大，你可以用git的版本试试，如果没问题就发布上去
