### ISSUE TITLE
Please help update the WCL Asia data of certain characters

### ISSUE THREAD

**Issue by KiddJin92** [icaca/WclPlayerScore-WotLK#51]
Please help update the WCL Asia data of certain characters
ID：帕博利珠单抗
ID：阿达木单抗
ID：司美格鲁肽

Server：亚服-古雷曼格

**Comment by icaca** [comment]
程序改动很大，你可以用git的版本试试，如果没问题就发布上去

**Comment by KiddJin92** [comment]
我试试

**Comment by KiddJin92** [comment]
![微信图片_20240423220113](https://github.com/icaca/WclPlayerScore-WotLK/assets/167729275/0959b9d3-cae2-47ce-aa88-6575caee70a4)
分数已经更新，但是百分比可能有点问题

**Comment by icaca** [comment]
百分比这两天更新

**Comment by KiddJin92** [comment]
![微信图片_20240425002910](https://github.com/icaca/WclPlayerScore-WotLK/assets/167729275/d4c93e81-a157-4652-a698-1fb075276fc5)
Hi, 百分比已经显示了，不过现在变成ICC+TOC了，之前是RS+ICC，以及之前有个亚服和服务器内名次显示，目前没显示名次。

**Comment by icaca** [comment]
嗯 nga之前征集大家建议，大家觉得icc和toc更有价值，rs数据不能体现玩家水平。
排名数据的确不全，明天再更新下。

**Comment by KiddJin92** [comment]
如果没有P4.5 TOC数据的角色，会显示RS+ICC吗？目前RS的评分还是主要为了帮忙评价熟练度的，毕竟这个阶段TOC的分数其实也没用

**Comment by icaca** [comment]
排名部分代码要重写，再等2天吧。目前wlk版本只有icc和toc的数据，没有获取rs的。

**Comment by KiddJin92** [comment]
![微信图片_20240425233033](https://github.com/icaca/WclPlayerScore-WotLK/assets/167729275/ce1f5b69-a9e1-4b2a-840c-6cf00ddd6a41)
排名也已经正常显示，辛苦！
